In [2]:
import numpy as np
# Tạo mảng NumPy kích thước 150x5 với các giá trị ngẫu nhiên
# Chiều cao (cm) từ 150 đến 190
# Cân nặng (kg) từ 40 đến 100
# Tuổi từ 18 đến 24
# Lương (VND) từ 5,000,000 đến 30,000,000
# GPA từ 1.0 đến 4.0

data = np.column_stack((
    np.random.randint(150, 191, 150),  # Chiều cao
    np.random.randint(40, 101, 150),   # Cân nặng
    np.random.randint(18, 25, 150),    # Tuổi từ 18 đến 24
    np.random.randint(5000000, 30000001, 150),  # Lương (VND)
    np.random.uniform(1.0, 4.0, 150)   # GPA
))

# Hiển thị 5 dòng đầu tiên của mảng NumPy
print(data[:5])

[[1.90000000e+02 5.30000000e+01 2.20000000e+01 2.13830410e+07
  3.29152999e+00]
 [1.73000000e+02 7.30000000e+01 1.90000000e+01 1.22331300e+07
  1.69717850e+00]
 [1.55000000e+02 6.40000000e+01 2.40000000e+01 2.95587020e+07
  3.52896822e+00]
 [1.54000000e+02 7.80000000e+01 2.00000000e+01 1.47801500e+07
  1.90773017e+00]
 [1.89000000e+02 7.00000000e+01 1.90000000e+01 2.66292020e+07
  1.36979799e+00]]


In [3]:
# Chia mảng thành X (bốn cột đầu tiên) và y (cột cuối cùng)
X = data[:, :-1]  # Lấy tất cả các dòng và bốn cột đầu tiên
y = data[:, -1]   # Lấy tất cả các dòng và chỉ cột cuối cùng

# Hiển thị X và y
print("X (Dữ liệu đầu vào):\n", X[:5])
print("y (Dữ liệu mục tiêu):\n", y[:5])

X (Dữ liệu đầu vào):
 [[1.9000000e+02 5.3000000e+01 2.2000000e+01 2.1383041e+07]
 [1.7300000e+02 7.3000000e+01 1.9000000e+01 1.2233130e+07]
 [1.5500000e+02 6.4000000e+01 2.4000000e+01 2.9558702e+07]
 [1.5400000e+02 7.8000000e+01 2.0000000e+01 1.4780150e+07]
 [1.8900000e+02 7.0000000e+01 1.9000000e+01 2.6629202e+07]]
y (Dữ liệu mục tiêu):
 [3.29152999 1.6971785  3.52896822 1.90773017 1.36979799]


In [5]:
from sklearn.model_selection import train_test_split
# Chia X thành X_train và X_test chứa 70% dữ liệu và chia y thành y_train và y_test, trong đó y_train chứa 70% dữ liệu
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Hiển thị kích thước của các tập dữ liệu
print("Kích thước của X_train:", X_train.shape)
print("Kích thước của X_test:", X_test.shape)
print("Kích thước của y_train:", y_train.shape)
print("Kích thước của y_test:", y_test.shape)

Kích thước của X_train: (105, 4)
Kích thước của X_test: (45, 4)
Kích thước của y_train: (105,)
Kích thước của y_test: (45,)


In [7]:
# Tạo 10 tập dữ liệu không chồng chéo của X_train
X_train_splits = np.array_split(X_train, 10)

# Hiển thị kích thước của các tập dữ liệu con
for i, split in enumerate(X_train_splits):
    print(f"Kích thước của tập con X_train_{i+1}: {split.shape}")

Kích thước của tập con X_train_1: (11, 4)
Kích thước của tập con X_train_2: (11, 4)
Kích thước của tập con X_train_3: (11, 4)
Kích thước của tập con X_train_4: (11, 4)
Kích thước của tập con X_train_5: (11, 4)
Kích thước của tập con X_train_6: (10, 4)
Kích thước của tập con X_train_7: (10, 4)
Kích thước của tập con X_train_8: (10, 4)
Kích thước của tập con X_train_9: (10, 4)
Kích thước của tập con X_train_10: (10, 4)
